name = "qMRI"
uuid = "659767e3-31a7-4dc1-8563-6e03f484b231"
authors = ["Aurélien Trotier <a.trotier@gmail.com>"]
version = "0.1.0"

[deps]
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"

[compat]
LsqFit = "0.12"
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
